# Generated by Django 5.2.4 on 2026-04-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="polloption",
            name="reference_id",
        ),
    ]
