site_name: CivicEdge
theme:
  name: material
nav:
  - Home: index.md
  - Vision: vision.md
  - About: about.md
  - Modules:
      - Citizen: 
        - Overview: modules/citizen/overview.md
        - Authentication: modules/citizen/authentication.md
        - Reporting Complaints: modules/citizen/complaint_system.md
        - Joining Volunteer Armies: modules/citizen/volunteer_system.md
        - Community Forum: modules/citizen/community_forum.md
        - Notifications: modules/citizen/notifications.md
        - profile_management: modules/citizen/profile_manage.md
      - Admin:
        - Overview: modules/admin/overview.md
        - Complaint Management: modules/admin/complaint_management.md
        - Solver Management: modules/admin/solver_management.md
        - User Management: modules/admin/user_management.md
        - Volunteer Management: modules/admin/volunteer_management.md
        - Reward Distribution: modules/admin/reward_distribution.md
        - Forum Moduration: modules/admin/forum_moderation.md
        - Poll Management: modules/admin/poll_management.md
        - Notification Broadcasts: modules/admin/notification_broadcasts.md
        - Notification Management: modules/admin/notification_management.md
        - Analytics Dashboard: modules/admin/analytics.md
        - Admin Profile: modules/admin/admin_profile.md
      - Solver:
        - Overview: modules/solver/overview.md
        - Complaint Handling: modules/solver/complaint_handling.md 
        - Complaint History: modules/solver/complaint_history.md 
        - Feedback View: modules/solver/feedback_view.md 
        - Profile Management: modules/solver/profile_management.md
        - Notifications: modules/solver/notifications.md
  - API:
      - Overview: api/overview.md
      - Citizen:
        - Complaint:
          - Overview: api\citizen\complaints\overview.md
          - Sumbit: api\citizen\complaints\submit.md
          - List Complaints: api\citizen\complaints\listcomplaints.md
          - Complaint Details: api\citizen\complaints\complaintdetails.md
          - Complaint Update: api\citizen\complaints\complaintupdate.md
          - Upload Media : api\citizen\complaints\upload_complaint_media.md
          - View Media : api\citizen\complaints\view_complaint_media.md
          - Status Log : api\citizen\complaints\view_complaint_status_log.md
          - Submit Feedback : api\citizen\complaints\submit_feedback.md
      - Solver:
        - Task:
          - Overview: api\solver\task\overview.md



