# -------- build stage --------
FROM node:20-alpine AS builder

WORKDIR /app/frontend
COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# -------- runtime stage --------
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/frontend/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]