# Generated by Django 5.2.4 on 2026-03-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer_army", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerevent",
            name="sponsor_logo_url",
            field=models.URLField(blank=True, help_text="Logo URL of the sponsor"),
        ),
        migrations.AddField(
            model_name="volunteerevent",
            name="sponsor_message",
            field=models.TextField(
                blank=True, help_text="Sponsor message or contribution details"
            ),
        ),
        migrations.AddField(
            model_name="volunteerevent",
            name="sponsor_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the sponsoring organization",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="volunteerevent",
            name="sponsor_website",
            field=models.URLField(blank=True, help_text="Website of the sponsor"),
        ),
    ]
