# Generated by Django 5.2.4 on 2026-03-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer_army", "0002_volunteerevent_sponsor_logo_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteergroup",
            name="description",
            field=models.TextField(),
        ),
    ]
