# Generated by Django 5.2.4 on 2026-03-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer_army", "0003_alter_volunteergroup_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipevidence",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
