# Generated by Django 5.2.4 on 2026-03-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer_army", "0004_alter_membershipevidence_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteermembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUBMITTED", "Submitted"),
                    ("ACTIVE", "Active"),
                    ("REJECTED", "Rejected"),
                    ("LEFT", "Left"),
                    ("REMOVED", "Removed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
