# Generated by Django 5.2.4 on 2026-03-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer_army", "0005_alter_volunteermembership_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteerevent",
            name="attendance_close_time",
        ),
        migrations.RemoveField(
            model_name="volunteerevent",
            name="attendance_open_time",
        ),
        migrations.AlterField(
            model_name="volunteerevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
