# Generated by Django 5.2.4 on 2026-03-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer_army", "0006_remove_volunteerevent_attendance_close_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerevent",
            name="location_address",
            field=models.TextField(),
        ),
    ]
