# Generated by Django 5.2.4 on 2026-03-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer_army", "0007_alter_volunteerevent_location_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventparticipation",
            name="status",
            field=models.CharField(
                choices=[
                    ("REGISTERED", "Registered"),
                    ("ATTENDANCE_SUBMITTED", "Attendance Submitted"),
                    ("VERIFIED", "Verified"),
                    ("REJECTED", "Rejected"),
                    ("NO_SHOW", "No Show"),
                ],
                db_index=True,
                default="REGISTERED",
                max_length=30,
            ),
        ),
    ]
