# Generated by Django 5.2.4 on 2026-03-20 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer_army", "0009_alter_eventparticipation_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteerrecognition",
            name="is_active",
        ),
        migrations.AddField(
            model_name="volunteerrecognition",
            name="emailed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="volunteerrecognition",
            name="status",
            field=models.CharField(
                choices=[("ISSUED", "Issued"), ("REVOKED", "Revoked")],
                default="ISSUED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="volunteerrecognition",
            name="issued_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issued_volunteer_recognitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="volunteerrecognition",
            name="recognition_type",
            field=models.CharField(
                choices=[
                    (
                        "EVENT_PARTICIPATION_CERTIFICATE",
                        "Event Participation Certificate",
                    )
                ],
                default="EVENT_PARTICIPATION_CERTIFICATE",
                max_length=50,
            ),
        ),
    ]
