# Generated by Django 5.2.4 on 2026-03-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer_army", "0010_remove_volunteerrecognition_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteermembership",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
