# Generated by Django 5.2.4 on 2026-03-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer_army", "0011_volunteermembership_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipevidence",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
