# Generated by Django 5.2.4 on 2026-04-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer_army", "0012_membershipevidence_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerrecognition",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("GENERATED", "Generated"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
