# Generated by Django 5.2.4 on 2026-04-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer_army", "0013_alter_volunteerrecognition_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerrecognition",
            name="certificate_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
