# Generated by Django 5.2.4 on 2026-04-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer_army", "0014_alter_volunteerrecognition_certificate_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerevent",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
