import { createApi } from "@reduxjs/toolkit/query/react";
import baseQueryWithReauth from "./baseQueryWithReauth";

export const baseApi = createApi({
  reducerPath: "api",
  baseQuery: baseQueryWithReauth({
    baseUrl: "/api/v1",
  }),
  refetchOnFocus: true,
  refetchOnReconnect: true,

  tagTypes: [
    "Summary",
    "Category",
    "IssueStep1",
    "Drafts",
    "Question",
    "Review",
    "Complaints",
    "Detail",
    "PendingIssues",
    "PendingIssueDetails",
    "PendingIssueDecision",
    "IssuesToSolvers",
    "Home",
    "Avatar",
    "Citizens",
    "Solvers",
    "Admins",
    "Zones",
    "SolverTasks",
    "SolverTaskDetail",
    "DraftProgress",
    "SolverDraftDetail",
    "PendingVerification",
    "PendingVerificationDetail",
    "Contractors",
    "SolverTaskProgressUpdates",
    "AdminFinalReport",
    "AdminFinalReportDetail",
    "AdminTask",
    "SolverDashboard",
    "VolunteerSummary",
    "VolunteerGroupList",
    "VolunteerGroupDetail",
    "VolunteerMembershipDetail",
    "VolunteerMembershipEvidenceList",
    "EventList",
    "EventDetails",
    "MyParticipation",
    "AdminGroupList",
    "AdminEventList",
    "ActiveGroupEventList",
    "AdminEventDetails",
    "AdminParcipantList",
    "AdminPendingMembership",
    "AdminMembershipPendingDetails",
    "AdminEventAttendance",
    "EventDetails",
    "MyRecognition",
    "MyGroups",
    "PollHome",
    "PollList",
    "PollDetails",
    "AdminFetchPolls",
    "AdminPollDetail",
    "AdminPollsDetailTimeLine",
    "AdminPollDetailDistribution",
    "NotificationCount",
    "NotificationList",
    "Posts",
    "Category",
    "PostDetails",
    "Comment",
    "MyActivity",
    "Reports",
    "ReportDetails",
    "AdminPosts",
    "AdminCategory",
    "ModerationLogs",
    "AdminActivityLogs",
    "AdminCategoryList",
    "AdminZoneList",
    "AdminBehavioralList",
    "AdminMetrics"
  ],

  endpoints: () => ({}),
});
