# Generated by Django 5.2.4 on 2026-02-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="draft_step",
            field=models.CharField(
                choices=[
                    ("BASIC", "Basic details"),
                    ("LOCATION", "Location"),
                    ("EVIDENCE", "Evidence"),
                    ("BEHAVIOR", "Behavioral Questions"),
                    ("REVIEW", "Review & Submit"),
                ],
                default="BASIC",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
    ]
