# Generated by Django 5.2.4 on 2026-02-19 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_issue_draft_step_issue_is_draft"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BehavioralPrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("YES_NO", "Yes No"),
                            ("MULTIPLE_CHOICE", "Multiple Choice"),
                            ("SCALE", "Scale"),
                            ("TEXT", "Text"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text="Used for multiple-choice or scale options",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = global prompt, else category-specific",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="issues.issuecategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssueAdministrativeDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("POSTPONED", "Postponed"),
                            ("BLOCKED", "Blocked"),
                            ("ESCALATED", "Escalated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "expected_review_date",
                    models.DateField(
                        blank=True,
                        help_text="When this issue will be revisited",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrative_decisions",
                        to="issues.issue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssueBehavioralResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("response_value", models.TextField()),
                ("optional_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavioral_responses",
                        to="issues.issue",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="issues.behavioralprompt",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("issue", "prompt")},
            },
        ),
    ]
