# Generated by Django 5.2.4 on 2026-02-19 15:43

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0003_behavioralprompt_issueadministrativedecision_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="issuecategory",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_issue_category_name_lower",
            ),
        ),
    ]
