# Generated by Django 5.2.4 on 2026-02-19 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0004_issuecategory_unique_issue_category_name_lower"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issues",
                to="issues.issuelocation",
            ),
        ),
    ]
