# Generated by Django 5.2.4 on 2026-02-20 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0005_alter_issue_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="location",
        ),
        migrations.AddField(
            model_name="issuelocation",
            name="issue",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="issues.issue",
            ),
        ),
    ]
