# Generated by Django 5.2.4 on 2026-02-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0006_remove_issue_location_issuelocation_issue"),
    ]

    operations = [
        migrations.AddField(
            model_name="issueadministrativedecision",
            name="public_message",
            field=models.CharField(
                default="user friendly decition message",
                help_text="Citizen-facing explanation of the current review state",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("IN_REVIEW", "In Review"),
                    ("IN_PROGRESS", "In Progress"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                    ("REOPENED", "Reopened"),
                ],
                db_index=True,
                default="OPEN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issuelog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CREATED", "Issue Created"),
                    ("CANCELLED", "Issue Cancelled"),
                    ("ACKNOWLEDGED", "Issue Acknowledged"),
                    ("REJECTED", "Issue Rejected"),
                    ("RESOLVED", "Issue Resolved"),
                    ("REOPENED", "Issue Reopened"),
                    ("EVIDENCE_ADDED", "Evidence Added"),
                    ("EVIDENCE_REJECTED", "Evidence Rejected"),
                    ("POST_PONED", "Issue Postponed"),
                ],
                max_length=30,
            ),
        ),
    ]
