# Generated by Django 5.2.4 on 2026-02-28 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0007_issueadministrativedecision_public_message_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="issueadministrativedecision",
            name="public_message",
            field=models.CharField(
                blank=True,
                help_text="Citizen-facing explanation of the current review state",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="issueevidence",
            name="evidence_type",
            field=models.CharField(
                choices=[("IMAGE", "Image"), ("VIDEO", "Video")],
                default="IMAGE",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="issueadministrativedecision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("issue",),
                name="one_active_admin_decision_per_issue",
            ),
        ),
    ]
