# Generated by Django 5.2.4 on 2026-03-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0008_alter_issueadministrativedecision_public_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issueadministrativedecision",
            name="context",
            field=models.CharField(
                choices=[
                    ("INITIAL_REVIEW", "Initial Review"),
                    ("VERIFICATION_REVIEW", "Verification Review"),
                    ("CLOSURE_REVIEW", "Closure Review"),
                ],
                db_index=True,
                default="INITIAL_REVIEW",
                max_length=30,
            ),
        ),
    ]
