# Generated by Django 5.2.4 on 2026-03-03 02:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0009_issueadministrativedecision_context"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="issueadministrativedecision",
            name="one_active_admin_decision_per_issue",
        ),
        migrations.AddConstraint(
            model_name="issueadministrativedecision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("issue", "context"),
                name="one_active_decision_per_issue_per_context",
            ),
        ),
    ]
