# Generated by Django 5.2.4 on 2026-03-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0011_issuetimelineevent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issuetimelineevent",
            name="event_type",
        ),
        migrations.AddField(
            model_name="issuetimelineevent",
            name="message",
            field=models.TextField(default="Issue successfully created"),
            preserve_default=False,
        ),
    ]
