# Generated by Django 5.2.4 on 2026-04-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0012_remove_issuetimelineevent_event_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuecategory",
            name="icon",
            field=models.CharField(max_length=100),
        ),
    ]
