# Generated by Django 5.2.4 on 2026-03-01 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("issues", "0008_alter_issueadministrativedecision_public_message_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Registered or commonly used contractor name",
                        max_length=255,
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=255)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        help_text="Type of work the contractor usually handles",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive contractors cannot be newly assigned",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SolverTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ASSIGNED", "Assigned"),
                            ("VERIFICATION_SUBMITTED", "Verification Submitted"),
                            ("APPROVED_FOR_EXECUTION", "Approved for Execution"),
                            ("IN_EXECUTION", "In Execution"),
                            ("COMPLETION_SUBMITTED", "Completion Submitted"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="ASSIGNED",
                        max_length=30,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "approved_duration_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "verification_rejection_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("completion_rejection_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solver_tasks_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solver_tasks",
                        to="issue_execution.contractor",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solver_tasks",
                        to="issues.issue",
                    ),
                ),
                (
                    "solver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_solver_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QualityFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("MULTIPLE_REJECTIONS", "Multiple Rejections"),
                            ("LONG_EXECUTION", "Long Execution Duration"),
                            ("FREQUENT_REOPEN", "Frequent Reopen"),
                            ("LOW_EVIDENCE_QUALITY", "Low Evidence Quality"),
                            ("UNUSUAL_ACTIVITY", "Unusual Activity"),
                            ("MANUAL_REVIEW", "Manual Review Required"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Human-readable explanation of why this flag was raised"
                    ),
                ),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acknowledged_quality_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_flags",
                        to="issues.issue",
                    ),
                ),
                (
                    "solver_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_flags",
                        to="issue_execution.solvertask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FieldVerificationReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_issue_present", models.BooleanField()),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("affected_area_description", models.TextField()),
                ("public_impact_summary", models.TextField()),
                (
                    "estimated_people_affected",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("local_feedback_summary", models.TextField(blank=True)),
                (
                    "estimated_budget",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("estimated_duration_days", models.PositiveIntegerField()),
                ("work_nature", models.CharField(max_length=100)),
                ("site_constraints", models.TextField(blank=True)),
                ("execution_risks", models.TextField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Only one active report per solver task"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_verification_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solver_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_reports",
                        to="issue_execution.solvertask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FieldVerificationDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ground_verification_completed", models.BooleanField(default=False)),
                ("impact_assessment_completed", models.BooleanField(default=False)),
                ("estimation_completed", models.BooleanField(default=False)),
                ("evidence_completed", models.BooleanField(default=False)),
                ("is_issue_present", models.BooleanField(null=True)),
                (
                    "severity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("affected_area_description", models.TextField(blank=True)),
                ("public_impact_summary", models.TextField(blank=True)),
                (
                    "estimated_people_affected",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("local_feedback_summary", models.TextField(blank=True)),
                (
                    "estimated_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "estimated_duration_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("work_nature", models.CharField(blank=True, max_length=100)),
                ("site_constraints", models.TextField(blank=True)),
                ("execution_risks", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="field_verification_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solver_task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_draft",
                        to="issue_execution.solvertask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExecutionProof",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completion_summary",
                    models.TextField(
                        help_text="Summary of work completed on the ground"
                    ),
                ),
                (
                    "deviations_from_plan",
                    models.TextField(
                        blank=True,
                        help_text="Any deviation from approved plan, if applicable",
                    ),
                ),
                (
                    "remaining_issues",
                    models.TextField(
                        blank=True,
                        help_text="Any remaining minor issues or follow-up notes",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only one active execution proof per solver task",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_execution_proofs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solver_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_proofs",
                        to="issue_execution.solvertask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskProgressUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "progress_summary",
                    models.TextField(
                        help_text="Description of work done or current status"
                    ),
                ),
                (
                    "progress_percentage",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional rough progress indicator (0–100)",
                        null=True,
                    ),
                ),
                (
                    "blockers",
                    models.TextField(
                        blank=True, help_text="Any blockers or delays encountered"
                    ),
                ),
                (
                    "next_steps",
                    models.TextField(
                        blank=True, help_text="Planned next steps, if any"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_progress_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solver_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_updates",
                        to="issue_execution.solvertask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        help_text="Cloudinary public_id for the asset", max_length=255
                    ),
                ),
                ("secure_url", models.URLField(help_text="Secure Cloudinary URL")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("format", models.CharField(blank=True, max_length=20)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("bytes", models.PositiveIntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_verification_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification_draft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="issue_execution.fieldverificationdraft",
                    ),
                ),
                (
                    "verification_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="issue_execution.fieldverificationreport",
                    ),
                ),
            ],
        ),
    ]
