# Generated by Django 5.2.4 on 2026-03-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue_execution", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldverificationdraft",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
    ]
