# Generated by Django 5.2.4 on 2026-03-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issue_execution", "0002_fieldverificationdraft_is_submitted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fieldverificationdraft",
            name="work_nature",
        ),
    ]
