# Generated by Django 5.2.4 on 2026-03-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue_execution", "0003_remove_fieldverificationdraft_work_nature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldverificationreport",
            name="work_nature",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
