# Generated by Django 5.2.4 on 2026-03-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue_execution", "0004_alter_fieldverificationreport_work_nature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solvertask",
            name="status",
            field=models.CharField(
                choices=[
                    ("ASSIGNED", "Assigned"),
                    ("VERIFICATION_SUBMITTED", "Verification Submitted"),
                    ("APPROVED_FOR_EXECUTION", "Approved for Execution"),
                    ("IN_EXECUTION", "In Execution"),
                    ("COMPLETION_SUBMITTED", "Completion Submitted"),
                    ("COMPLETED", "Completed"),
                    ("TERMINATED", "Terminated"),
                ],
                db_index=True,
                default="ASSIGNED",
                max_length=30,
            ),
        ),
    ]
