# Generated by Django 5.2.4 on 2026-03-04 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue_execution", "0006_executionevidence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="executionproof",
            name="admin_message",
            field=models.TextField(
                blank=True, help_text="Reason provided by admin if proof is rejected"
            ),
        ),
        migrations.AddField(
            model_name="executionproof",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="executionproof",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_execution_proofs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
