# Generated by Django 5.2.4 on 2026-03-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue_execution", "0007_executionproof_admin_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executionproof",
            name="admin_message",
            field=models.TextField(
                blank=True,
                default="Please wait for admin review",
                help_text="Reason provided by admin if proof is rejected",
            ),
        ),
    ]
