class NotificationEvent:
    ISSUE_REPORTED = "ISSUE_REPORTED"
    TASK_ASSIGNED_TO_SOLVER = "TASK_ASSIGNED_TO_SOLVER"
    REPORT_SUBMITTED_TO_ADMIN = "REPORT_SUBMITTED_TO_ADMIN"
    TASK_COMPLETED_BY_SOLVER = "TASK_COMPLETED_BY_SOLVER"
    ISSUE_RESOLVED = "ISSUE_RESOLVED"
    TASK_APPROVED_BY_ADMIN = "TASK_APPROVED_BY_ADMIN" 
    TASK_REJECTED_BY_ADMIN = "TASK_REJECTED_BY_ADMIN"

    VOLUNTEER_JOIN_APPROVED = "VOLUNTEER_JOIN_APPROVED"
    VOLUNTEER_JOIN_REJECTED = "VOLUNTEER_JOIN_REJECTED"
    VOLUNTEER_EVENT_REMINDER = "VOLUNTEER_EVENT_REMINDER"
    VOLUNTEER_CERTIFICATE = "VOLUNTEER_CERTIFICATE", "Volunteer Certificate"    

    FORUM_REPLY_RECEIVED = "FORUM_REPLY_RECEIVED"
    FORUM_POST_REACTED = "FORUM_POST_REACTED"
    FORUM_POST_CREATED = "FORUM_POST_CREATED"
    FORUM_REPORT_USER = "FORUM_REPORT_USER"

    PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
    PAYMENT_FAILED = "PAYMENT_FAILED"

    ADMIN_ANNOUNCEMENT = "ADMIN_ANNOUNCEMENT"