# Generated by Django 5.2.4 on 2026-04-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notification",
            "0004_notification_type_alter_notification_target_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("ISSUE_REPORTED", "Issue Reported"),
                    ("TASK_ASSIGNED_TO_SOLVER", "Task Assigned To Solver"),
                    ("REPORT_SUBMITTED_TO_ADMIN", "Report Submitted To Admin"),
                    ("TASK_COMPLETED_BY_SOLVER", "Task Completed By Solver"),
                    ("ISSUE_RESOLVED", "Issue Resolved"),
                    ("VOLUNTEER_JOIN_APPROVED", "Volunteer Join Approved"),
                    ("VOLUNTEER_EVENT_REMINDER", "Volunteer Event Reminder"),
                    ("FORUM_REPLY_RECEIVED", "Forum Reply Received"),
                    ("FORUM_POST_CREATED", "Forum Post Created"),
                    ("PAYMENT_SUCCESS", "Payment Success"),
                    ("PAYMENT_FAILED", "Payment Failed"),
                    ("ADMIN_ANNOUNCEMENT", "Admin Announcement"),
                ],
                max_length=50,
            ),
        ),
    ]
