# Generated by Django 5.2.4 on 2026-04-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0005_alter_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("ISSUE", "Issue"),
                    ("TASK", "Task"),
                    ("FORUM", "Forum"),
                    ("PAYMENT", "Payment"),
                    ("VOLUNTEER", "Volunteer"),
                ],
                max_length=20,
            ),
        ),
    ]
