# Generated by Django 5.2.4 on 2026-04-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0008_alter_notification_target_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("ISSUE", "Issue"),
                    ("TASK", "Task"),
                    ("REPORT", "Report"),
                    ("RESOLVED_ISSUE", "Resolved Issue"),
                    ("TASK_APPROVAL", "Task Approval"),
                    ("TASK_REJECTION", "Task Rejection"),
                    ("VOLUNTEER_APPROVED", "Volunteer Approved"),
                    ("VOLUNTEER_REJECTION", "Volunteer Rejection"),
                    ("VOLUNTEER_REMINDER", "Volunteer Reminder"),
                    ("FORUM", "Forum"),
                    ("PAYMENT", "Payment"),
                    ("VOLUNTEER", "Volunteer"),
                    ("VOLUNTEER_CERTIFICATE", "Volunteer Certificate"),
                ],
                max_length=40,
            ),
        ),
    ]
