# Generated by Django 5.2.4 on 2026-04-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0010_alter_notification_target_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("ISSUE_REPORTED", "Issue Reported"),
                    ("TASK_ASSIGNED_TO_SOLVER", "Task Assigned To Solver"),
                    ("REPORT_SUBMITTED_TO_ADMIN", "Report Submitted To Admin"),
                    ("TASK_COMPLETED_BY_SOLVER", "Task Completed By Solver"),
                    ("ISSUE_RESOLVED", "Issue Resolved"),
                    ("TASK_APPROVED_BY_ADMIN", "Task Approved By Admin"),
                    ("TASK_REJECTED_BY_ADMIN", "Task Rejected By Admin"),
                    ("VOLUNTEER_JOIN_APPROVED", "Volunteer Join Approved"),
                    ("VOLUNTEER_EVENT_REMINDER", "Volunteer Event Reminder"),
                    ("VOLUNTEER_JOIN_REJECTED", "Volunteer Join Rejected"),
                    ("VOLUNTEER_CERTIFICATE", "Volunteer Certificate"),
                    ("FORUM_REPLY_RECEIVED", "Forum Reply Received"),
                    ("FORUM_POST_CREATED", "Forum Post Created"),
                    ("FORUM_REPORT_USER", "Forum Report User"),
                    ("FORUM_REACTED", "Forum Reacted"),
                    ("PAYMENT_SUCCESS", "Payment Success"),
                    ("PAYMENT_FAILED", "Payment Failed"),
                    ("ADMIN_ANNOUNCEMENT", "Admin Announcement"),
                ],
                max_length=50,
            ),
        ),
    ]
