# Generated by Django 5.2.4 on 2026-04-17 06:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0011_alter_notification_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityFeed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        choices=[
                            ("ISSUE", "Issue"),
                            ("TASK", "Task"),
                            ("POLL", "Poll"),
                            ("FORUM", "Forum"),
                            ("GROUP", "Group"),
                            ("EVENT", "Event"),
                            ("USER", "User"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("UPDATED", "Updated"),
                            ("JOINED", "Joined"),
                            ("VOTED", "Voted"),
                            ("COMMENTED", "Commented"),
                            ("LIKED", "Liked"),
                            ("ASSIGNED", "Assigned"),
                            ("COMPLETED", "Completed"),
                            ("CLOSED", "Closed"),
                            ("MODERATED", "Moderated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
