# Generated by Django 5.2.4 on 2026-04-11 17:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "forum_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ForumPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("hidden", "Hidden"),
                            ("removed", "Removed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_highlighted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="forum.forumcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forum_posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("hidden", "Hidden"),
                            ("removed", "Removed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="forum.forumcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="forum.forumpost",
                    ),
                ),
            ],
            options={
                "db_table": "forum_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("appreciate", "Appreciate"),
                            ("important", "Important"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="forum.forumpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forum_reactions",
            },
        ),
        migrations.CreateModel(
            name="ForumReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("post", "Post"), ("comment", "Comment")],
                        max_length=20,
                    ),
                ),
                ("target_id", models.UUIDField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forum_reports",
            },
        ),
        migrations.CreateModel(
            name="ModerationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("post", "Post"),
                            ("comment", "Comment"),
                            ("user", "User"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_id", models.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("hide", "Hide"),
                            ("remove", "Remove"),
                            ("restore", "Restore"),
                            ("warn", "Warn"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "moderation_logs",
            },
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(
                fields=["created_at"], name="forum_posts_created_61a79a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(
                fields=["category"], name="forum_posts_categor_c37b24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(fields=["status"], name="forum_posts_status_e1e8c5_idx"),
        ),
        migrations.AddIndex(
            model_name="forumcomment",
            index=models.Index(fields=["post"], name="forum_comme_post_id_b28739_idx"),
        ),
        migrations.AddIndex(
            model_name="forumcomment",
            index=models.Index(
                fields=["created_at"], name="forum_comme_created_0f30f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forumcomment",
            index=models.Index(fields=["status"], name="forum_comme_status_dbbb9d_idx"),
        ),
        migrations.AddIndex(
            model_name="forumreaction",
            index=models.Index(fields=["post"], name="forum_react_post_id_068886_idx"),
        ),
        migrations.AddIndex(
            model_name="forumreaction",
            index=models.Index(fields=["user"], name="forum_react_user_id_267200_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="forumreaction",
            unique_together={("user", "post")},
        ),
        migrations.AddIndex(
            model_name="forumreport",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="forum_repor_target__6a7b42_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forumreport",
            index=models.Index(fields=["status"], name="forum_repor_status_25a469_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="forumreport",
            unique_together={("reported_by", "target_type", "target_id")},
        ),
        migrations.AddIndex(
            model_name="moderationlog",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="moderation__target__c792da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="moderationlog",
            index=models.Index(
                fields=["moderator"], name="moderation__moderat_2e39da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationlog",
            index=models.Index(
                fields=["created_at"], name="moderation__created_7de476_idx"
            ),
        ),
    ]
