# Generated by Django 5.2.4 on 2026-04-11 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumPostMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("public_id", models.CharField(max_length=255, unique=True)),
                ("url", models.URLField(max_length=500)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("format", models.CharField(blank=True, max_length=20, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="forum.forumpost",
                    ),
                ),
            ],
            options={
                "db_table": "forum_post_media",
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["post"], name="forum_post__post_id_bba52e_idx"
                    ),
                    models.Index(
                        fields=["public_id"], name="forum_post__public__d8ee2f_idx"
                    ),
                ],
            },
        ),
    ]
