# ---------- DEV IMAGE ----------
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# system deps (dev-friendly)
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app/backend

# install python deps
COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

# copy source
COPY backend/ /app/backend/

# dev server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
