# Generated by Django 5.2.4 on 2025-07-26 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='admin_zone_responsibility',
            field=models.CharField(blank=True, help_text='Zones managed by admin', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Profile picture URL', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.JSONField(blank=True, help_text="List of user's interests", null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Valid 10-digit Indian mobile number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian phone number starting with 6-9.', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.JSONField(blank=True, help_text='List of technical or civic skills', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Access to admin site'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('solver', 'Solver'), ('admin', 'Admin')], default='citizen', help_text='User role: citizen, solver, or admin', max_length=20),
        ),
    ]
