# Generated by Django 5.2.4 on 2026-02-13 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_remove_profile_location_profile_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Valid 10-digit Indian mobile number",
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid 10-digit Indian phone number starting with 6-9.",
                        regex="^[6-9]\\d{9}$",
                    )
                ],
            ),
        ),
    ]
