# Generated by Django 5.2.4 on 2026-02-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_alter_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
