# Generated by Django 5.2.4 on 2026-02-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reference_id",
            field=models.CharField(
                db_index=True, default=1, editable=False, max_length=20
            ),
        ),
    ]
