# Generated by Django 5.2.4 on 2026-02-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_user_reference_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="reference_id",
            field=models.CharField(
                db_index=True, editable=False, max_length=20, unique=True
            ),
        ),
    ]
