# Generated by Django 5.2.4 on 2026-02-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_alter_user_reference_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zone",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
