# Generated by Django 5.2.4 on 2026-04-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_alter_zone_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
