name: Django CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        options: >-
          --health-cmd "pg_isready -U testuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_NAME: testdb
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_HOST: localhost
      DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: config.settings.development
      GITHUB_ACTIONS: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt
        working-directory: backend

      - name: Wait for Postgres
        run: |
          echo "Waiting for PostgreSQL to become ready..."
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U testuser; then
              echo "PostgreSQL is ready!"
              break
            else
              echo "PostgreSQL not ready yet... ($i)"
              sleep 2
            fi
          done

      - name: Run migrations
        run: python manage.py migrate
        working-directory: backend

      - name: Run tests
        run: python manage.py test
        working-directory: backend
