name: Django CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      GITHUB_ACTIONS: true
      DB_NAME: testdb
      DB_USER: testuser
      DB_PASSWORD: testpassword
      DB_HOST: localhost
      DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: config.settings.development

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff  # ✅ Add this line
        working-directory: .

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U $DB_USER; do
            echo "Waiting for Postgres..."
            sleep 1
          done
        working-directory: backend

      - name: Run Django migrations
        run: python manage.py migrate
        working-directory: backend

      - name: Run Ruff (Linter)
        run: ruff check .
        working-directory: backend


      - name: Run tests
        run: python manage.py test
        working-directory: backend
