name: Django CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      GITHUB_ACTIONS: true
      DB_NAME: testdb
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_HOST: 127.0.0.1 
      DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: config.settings.development

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt
        working-directory: backend

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Try connecting manually
        run: |
         echo "Trying to manually connect to postgres..."
         PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c '\l'


      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h postgres -p 5432 -U testuser; do
            echo "Waiting for Postgres..."
            sleep 1
          done

      - name: Run Django migrations
        run: python manage.py migrate
        working-directory: backend

      - name: Run tests
        run: python manage.py test
        working-directory: backend
